// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgtkpxegywyrkzjaimls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndndGtweGVneXd5cmt6amFpbWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NTcxOTYsImV4cCI6MjA3MTMzMzE5Nn0.NckF5D4lR3fmEqoSQCdxgblTmoTYA32zU1rJTHLxrTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});